### ISSUE TITLE
Plugin does not work on Gradle 8.0

### ISSUE THREAD

**Issue by britter** [google/protobuf-gradle-plugin#612]
Testing the plugin with the lastest Gradle 8.0 nightly yields:

`java.lang.NoSuchMethodError: 'java.util.Set org.gradle.plugins.ide.idea.model.IdeaModule.getTestSourceDirs()'`

It looks like this is happening [here](https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/Utils.groovy#L112). This code needs check whether it's running on Gradle 8.0 and if so, it need to use the new API called `testSources`: https://github.com/gradle/gradle/blob/5eb959671e9d45827b9482e5003c8572410551ab/subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java#L321-L329

**Comment by rougsig** [comment]
Ouch. Gradle 8 already released?  I'll see what can be done to fix it.

**Comment by britter** [comment]
@rougsig no it's not released yet. I was just testing compatibility in our build with a nightly of Gradle 8.0 because it's not too far up the horizon.

**Comment by ejona86** [comment]
Fixed by #617
